/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/admin-api';
export * from './apis/face-api';
export * from './apis/media-api';
export * from './apis/person-api';
export * from './apis/recognize-api';
export * from './apis/transform-api';

