/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Usage } from '../models';
/**
 * AdminApi - axios parameter creator
 * @export
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary get API usage information. (Administrative endpoint - API secret required)
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} apiSecret your API secret. It is not recommended to expose your application secret at client side.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2AdminUsageGet: async (apiKey: string, apiSecret: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiKey' is not null or undefined
            if (apiKey === null || apiKey === undefined) {
                throw new RequiredError('apiKey','Required parameter apiKey was null or undefined when calling v2AdminUsageGet.');
            }
            // verify required parameter 'apiSecret' is not null or undefined
            if (apiSecret === null || apiSecret === undefined) {
                throw new RequiredError('apiSecret','Required parameter apiSecret was null or undefined when calling v2AdminUsageGet.');
            }
            const localVarPath = `/v2/admin/usage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (apiKey !== undefined) {
                localVarQueryParameter['api_key'] = apiKey;
            }

            if (apiSecret !== undefined) {
                localVarQueryParameter['api_secret'] = apiSecret;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 * @export
 */
export const AdminApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary get API usage information. (Administrative endpoint - API secret required)
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} apiSecret your API secret. It is not recommended to expose your application secret at client side.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2AdminUsageGet(apiKey: string, apiSecret: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Usage>>> {
            const localVarAxiosArgs = await AdminApiAxiosParamCreator(configuration).v2AdminUsageGet(apiKey, apiSecret, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AdminApi - factory interface
 * @export
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary get API usage information. (Administrative endpoint - API secret required)
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} apiSecret your API secret. It is not recommended to expose your application secret at client side.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2AdminUsageGet(apiKey: string, apiSecret: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Usage>> {
            return AdminApiFp(configuration).v2AdminUsageGet(apiKey, apiSecret, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminApi - object-oriented interface
 * @export
 * @class AdminApi
 * @extends {BaseAPI}
 */
export class AdminApi extends BaseAPI {
    /**
     * 
     * @summary get API usage information. (Administrative endpoint - API secret required)
     * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
     * @param {string} apiSecret your API secret. It is not recommended to expose your application secret at client side.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public async v2AdminUsageGet(apiKey: string, apiSecret: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Usage>> {
        return AdminApiFp(this.configuration).v2AdminUsageGet(apiKey, apiSecret, options).then((request) => request(this.axios, this.basePath));
    }
}
