/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Person } from '../models';
import { SetPerson } from '../models';
/**
 * PersonApi - axios parameter creator
 * @export
 */
export const PersonApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} apiSecret your API secret. It is not recommended to expose your application secret at client side.
         * @param {Array<string>} [personId] (optional) query parameters array of specific person ids or all@namespace to list persons in that namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2PersonGet: async (apiKey: string, apiSecret: string, personId?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiKey' is not null or undefined
            if (apiKey === null || apiKey === undefined) {
                throw new RequiredError('apiKey','Required parameter apiKey was null or undefined when calling v2PersonGet.');
            }
            // verify required parameter 'apiSecret' is not null or undefined
            if (apiSecret === null || apiSecret === undefined) {
                throw new RequiredError('apiSecret','Required parameter apiSecret was null or undefined when calling v2PersonGet.');
            }
            const localVarPath = `/v2/person`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (apiKey !== undefined) {
                localVarQueryParameter['api_key'] = apiKey;
            }

            if (apiSecret !== undefined) {
                localVarQueryParameter['api_secret'] = apiSecret;
            }

            if (personId) {
                localVarQueryParameter['person_id'] = personId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary sets or overwrites person id for each specified face.
         * @param {SetPerson} [body] request json body with parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2PersonPost: async (body?: SetPerson, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/person`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PersonApi - functional programming interface
 * @export
 */
export const PersonApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} apiSecret your API secret. It is not recommended to expose your application secret at client side.
         * @param {Array<string>} [personId] (optional) query parameters array of specific person ids or all@namespace to list persons in that namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2PersonGet(apiKey: string, apiSecret: string, personId?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Person>>>> {
            const localVarAxiosArgs = await PersonApiAxiosParamCreator(configuration).v2PersonGet(apiKey, apiSecret, personId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary sets or overwrites person id for each specified face.
         * @param {SetPerson} [body] request json body with parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2PersonPost(body?: SetPerson, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PersonApiAxiosParamCreator(configuration).v2PersonPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PersonApi - factory interface
 * @export
 */
export const PersonApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} apiSecret your API secret. It is not recommended to expose your application secret at client side.
         * @param {Array<string>} [personId] (optional) query parameters array of specific person ids or all@namespace to list persons in that namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2PersonGet(apiKey: string, apiSecret: string, personId?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Person>>> {
            return PersonApiFp(configuration).v2PersonGet(apiKey, apiSecret, personId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary sets or overwrites person id for each specified face.
         * @param {SetPerson} [body] request json body with parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2PersonPost(body?: SetPerson, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PersonApiFp(configuration).v2PersonPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PersonApi - object-oriented interface
 * @export
 * @class PersonApi
 * @extends {BaseAPI}
 */
export class PersonApi extends BaseAPI {
    /**
     * 
     * @summary lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)
     * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
     * @param {string} apiSecret your API secret. It is not recommended to expose your application secret at client side.
     * @param {Array<string>} [personId] (optional) query parameters array of specific person ids or all@namespace to list persons in that namespace
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonApi
     */
    public async v2PersonGet(apiKey: string, apiSecret: string, personId?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Person>>> {
        return PersonApiFp(this.configuration).v2PersonGet(apiKey, apiSecret, personId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary sets or overwrites person id for each specified face.
     * @param {SetPerson} [body] request json body with parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonApi
     */
    public async v2PersonPost(body?: SetPerson, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PersonApiFp(this.configuration).v2PersonPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
