/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Recognize } from '../models';
import { RecognizeRequest } from '../models';
/**
 * RecognizeApi - axios parameter creator
 * @export
 */
export const RecognizeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary gets a faces recognition result.
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} recognizeUuid the requested recognize identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2RecognizeGet: async (apiKey: string, recognizeUuid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiKey' is not null or undefined
            if (apiKey === null || apiKey === undefined) {
                throw new RequiredError('apiKey','Required parameter apiKey was null or undefined when calling v2RecognizeGet.');
            }
            // verify required parameter 'recognizeUuid' is not null or undefined
            if (recognizeUuid === null || recognizeUuid === undefined) {
                throw new RequiredError('recognizeUuid','Required parameter recognizeUuid was null or undefined when calling v2RecognizeGet.');
            }
            const localVarPath = `/v2/recognize`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (apiKey !== undefined) {
                localVarQueryParameter['api_key'] = apiKey;
            }

            if (recognizeUuid !== undefined) {
                localVarQueryParameter['recognize_uuid'] = recognizeUuid;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary initiate recognition for one or more faces
         * @param {RecognizeRequest} [body] request json body with parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2RecognizePost: async (body?: RecognizeRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/recognize`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecognizeApi - functional programming interface
 * @export
 */
export const RecognizeApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary gets a faces recognition result.
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} recognizeUuid the requested recognize identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2RecognizeGet(apiKey: string, recognizeUuid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await RecognizeApiAxiosParamCreator(configuration).v2RecognizeGet(apiKey, recognizeUuid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary initiate recognition for one or more faces
         * @param {RecognizeRequest} [body] request json body with parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2RecognizePost(body?: RecognizeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Recognize>>> {
            const localVarAxiosArgs = await RecognizeApiAxiosParamCreator(configuration).v2RecognizePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RecognizeApi - factory interface
 * @export
 */
export const RecognizeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary gets a faces recognition result.
         * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
         * @param {string} recognizeUuid the requested recognize identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2RecognizeGet(apiKey: string, recognizeUuid: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return RecognizeApiFp(configuration).v2RecognizeGet(apiKey, recognizeUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary initiate recognition for one or more faces
         * @param {RecognizeRequest} [body] request json body with parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2RecognizePost(body?: RecognizeRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<Recognize>> {
            return RecognizeApiFp(configuration).v2RecognizePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecognizeApi - object-oriented interface
 * @export
 * @class RecognizeApi
 * @extends {BaseAPI}
 */
export class RecognizeApi extends BaseAPI {
    /**
     * 
     * @summary gets a faces recognition result.
     * @param {string} apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236
     * @param {string} recognizeUuid the requested recognize identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecognizeApi
     */
    public async v2RecognizeGet(apiKey: string, recognizeUuid: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return RecognizeApiFp(this.configuration).v2RecognizeGet(apiKey, recognizeUuid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary initiate recognition for one or more faces
     * @param {RecognizeRequest} [body] request json body with parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecognizeApi
     */
    public async v2RecognizePost(body?: RecognizeRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<Recognize>> {
        return RecognizeApiFp(this.configuration).v2RecognizePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
