/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Face } from './face';
/**
 * represents a cropped face information.
 * @export
 * @interface CroppedFace
 */
export interface CroppedFace {
    /**
     * base64 encoded cropped face image file (jpg or png).
     * @type {string}
     * @memberof CroppedFace
     */
    imageBase64?: string;
    /**
     * 
     * @type {Face}
     * @memberof CroppedFace
     */
    face?: Face;
}
