/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents an error information.
 * @export
 * @interface Error
 */
export interface Error {
    /**
     * error code
     * @type {number}
     * @memberof Error
     */
    errorCode?: number;
    /**
     * error error description
     * @type {string}
     * @memberof Error
     */
    errorDescription?: string;
}
