/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Media } from './media';
import { Recognize } from './recognize';
/**
 * 
 * @export
 * @interface MediaUploadResponse
 */
export interface MediaUploadResponse {
    /**
     * 
     * @type {Media}
     * @memberof MediaUploadResponse
     */
    media?: Media;
    /**
     * 
     * @type {Recognize}
     * @memberof MediaUploadResponse
     */
    recognize?: Recognize;
}
