/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MediaFileBody
 */
export interface MediaFileBody {
    /**
     * your API key or d45fd466-51e2-4701-8da8-04351c872236
     * @type {string}
     * @memberof MediaFileBody
     */
    apiKey: string;
    /**
     * a media file to upload
     * @type {Blob}
     * @memberof MediaFileBody
     */
    file: Blob;
    /**
     * (optional) comma separated list of detection flags: bestface - return only face with highest detection score, centerface - same as bestface but gives preference to face closest to image center, basicpoints - 22 basic points detection, propoints - 101 pro points detection, classifiers - face classification and attributes, extended - extended color and geometric measurements, content - image content detection.  for example: \"basicpoints,propoints,classifiers,content\"
     * @type {string}
     * @memberof MediaFileBody
     */
    detectionFlags?: string;
    /**
     * (optional) filter faces with detection score lower than min_score.
     * @type {number}
     * @memberof MediaFileBody
     */
    detectionMinScore?: number;
    /**
     * (optional) override automatic faces detection and manually specify faces locations, face points and person ids to assign.  provide a list of new faces as a string of comma separated entries with following template: { \"x\": 0, \"y\": 0, \"width\": 0, \"height\": 0, \"angle\": 0, \"points\": [ { \"x\": 0, \"y\": 0, \"type\": 0 }, { \"x\": 0, \"y\": 0, \"type\": 0 }], \"tags\": [ { \"name\": \"\",  \"value\": \"\",  \"confidence\": 1.0 }, {\"name\": \"\", \"value\": \"\", \"confidence\": 1.0 } ], \"set_person_id\": \"\"}
     * @type {string}
     * @memberof MediaFileBody
     */
    detectionNewFaces?: string;
    /**
     * (optional) set person id in format name@namespace to each detected face. recommended to use with detection_flags bestface, centerface and/or min_score minimum detection score parameter. you can use special name random@namespace to assign random unique name to each face in specific namespace.  for example: \"John Doe@mynamespace\"
     * @type {string}
     * @memberof MediaFileBody
     */
    setPersonId?: string;
    /**
     * (optional) for each detected face run recognize against specified targets (face ids, person ids or namespaces).  provide a list of targets as comma separated string, for example \"all@mynamespace,John Doe@othernamespace\"
     * @type {string}
     * @memberof MediaFileBody
     */
    recognizeTargets?: string;
    /**
     * (optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \"min_match_score:0.4,min_score:0.2,gender:male,race:white\"
     * @type {string}
     * @memberof MediaFileBody
     */
    recognizeParameters?: string;
    /**
     * (optional) original media filename, path, uri or your application specific id that you want to be stored in media metadata for reference.
     * @type {string}
     * @memberof MediaFileBody
     */
    originalFilename?: string;
}
