/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Face } from './face';
import { TagMedia } from './tag-media';
/**
 * represents a media information.
 * @export
 * @interface Media
 */
export interface Media {
    /**
     * media unique identifier.
     * @type {string}
     * @memberof Media
     */
    mediaUuid?: string;
    /**
     * media content hash value.
     * @type {string}
     * @memberof Media
     */
    checksum?: string;
    /**
     * collection of detected or labelled faces.
     * @type {Array<Face>}
     * @memberof Media
     */
    faces?: Array<Face>;
    /**
     * collection of media tags.
     * @type {Array<TagMedia>}
     * @memberof Media
     */
    tags?: Array<TagMedia>;
    /**
     * reference original media filename, path, uri or your application specific id that was provided during media upload.
     * @type {string}
     * @memberof Media
     */
    originalFilename?: string;
    /**
     * reserved for future video processing
     * @type {string}
     * @memberof Media
     */
    duration?: string;
}
