/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Point } from './point';
import { Tag } from './tag';
/**
 * represents a manually labelled face information. face bounding box will be estimated if not provided. minimum 3 points (eyes, mouth) are required.
 * @export
 * @interface NewFace
 */
export interface NewFace {
    /**
     * x coordinate of the face bounding box center in pixels.
     * @type {number}
     * @memberof NewFace
     */
    x?: number;
    /**
     * y coordinate of the face bounding box center in pixels.
     * @type {number}
     * @memberof NewFace
     */
    y?: number;
    /**
     * width of the face bounding box center in pixels.
     * @type {number}
     * @memberof NewFace
     */
    width?: number;
    /**
     * height of the face bounding box center in pixels.
     * @type {number}
     * @memberof NewFace
     */
    height?: number;
    /**
     * in-plane rotation (roll) of the face bounding box center in degrees.
     * @type {number}
     * @memberof NewFace
     */
    angle?: number;
    /**
     * face points. you have to specify minimum 3 points coordinates - type 512 (left eye), type 768 (right eye), type 2816 (mouth). point names are not required.
     * @type {Array<Point>}
     * @memberof NewFace
     */
    points: Array<Point>;
    /**
     * (optional) face tags or labels to set manually.
     * @type {Array<Tag>}
     * @memberof NewFace
     */
    tags?: Array<Tag>;
    /**
     * (optional) manually assign person id in format name@namespace.
     * @type {string}
     * @memberof NewFace
     */
    setPersonId?: string;
}
