/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents a person information.
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * person identifier
     * @type {string}
     * @memberof Person
     */
    personId?: string;
    /**
     * list of face uuids with this person assigned
     * @type {Array<string>}
     * @memberof Person
     */
    facesUuids?: Array<string>;
}
