/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents a recognition request for one or more faces.
 * @export
 * @interface RecognizeRequest
 */
export interface RecognizeRequest {
    /**
     * your API key or d45fd466-51e2-4701-8da8-04351c872236
     * @type {string}
     * @memberof RecognizeRequest
     */
    apiKey: string;
    /**
     * list of face unique identifiers that should be recognized.
     * @type {Array<string>}
     * @memberof RecognizeRequest
     */
    facesUuids: Array<string>;
    /**
     * list of recognition targets which can include face identifiers, fully qualified person ids in format name@namespace or entire namespaces in format all@namespace.
     * @type {Array<string>}
     * @memberof RecognizeRequest
     */
    targets: Array<string>;
    /**
     * (optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \"min_match_score:0.4,min_score:0.2,gender:male,race:white\"
     * @type {string}
     * @memberof RecognizeRequest
     */
    parameters?: string;
}
