/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RecognizeResult } from './recognize-result';
/**
 * represents a recognition results for one or more faces.
 * @export
 * @interface Recognize
 */
export interface Recognize {
    /**
     * recognize request unique identifier.
     * @type {string}
     * @memberof Recognize
     */
    recognizeUuid?: string;
    /**
     * collection of recognize results.
     * @type {Array<RecognizeResult>}
     * @memberof Recognize
     */
    results?: Array<RecognizeResult>;
}
