/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents a set person call body parameters.
 * @export
 * @interface SetPerson
 */
export interface SetPerson {
    /**
     * your API key or d45fd466-51e2-4701-8da8-04351c872236
     * @type {string}
     * @memberof SetPerson
     */
    apiKey: string;
    /**
     * list of face uuids to set person id. each face can have only one person id assigned to it. setting a person id overwrites the old value.
     * @type {Array<string>}
     * @memberof SetPerson
     */
    facesUuids: Array<string>;
    /**
     * person id in format name@namespace. name and namespace can include letters, numbers, dots, underscores and spaces. special name random@namespace could be used to assign random person name with specific namespace. Namespace part should not exceed 60 characters. Name part should not exceed 200 characters. Setting person_id to empty string resets the person id. Faces will be permanently stored for as long as person id is assigned to them. Faces without person ids will be deleted starting from 24 hours. Resetting person id on faces generated more than 24 hours ago may immediately delete the. When face is assigned to/removed from namespace search indexes of namespaces involved will asynchrously update. It may take from seconds to serveral minutes depending on namespace size for changes to propagate.
     * @type {string}
     * @memberof SetPerson
     */
    personId?: string;
}
