/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents a media or object tag.
 * @export
 * @interface TagMedia
 */
export interface TagMedia {
    /**
     * tag name.
     * @type {string}
     * @memberof TagMedia
     */
    name?: string;
    /**
     * tag value.
     * @type {string}
     * @memberof TagMedia
     */
    value?: string;
    /**
     * tag confidence, if automatically detected, otherwise 1.0.
     * @type {number}
     * @memberof TagMedia
     */
    confidence?: number;
    /**
     * reserved for future use
     * @type {number}
     * @memberof TagMedia
     */
    x?: number;
    /**
     * reserved for future use
     * @type {number}
     * @memberof TagMedia
     */
    y?: number;
    /**
     * reserved for future use
     * @type {number}
     * @memberof TagMedia
     */
    width?: number;
    /**
     * reserved for future use
     * @type {number}
     * @memberof TagMedia
     */
    height?: number;
    /**
     * reserved for future use
     * @type {number}
     * @memberof TagMedia
     */
    angle?: number;
    /**
     * reserved for future use
     * @type {number}
     * @memberof TagMedia
     */
    instanceId?: number;
    /**
     * reserved for future video processing
     * @type {string}
     * @memberof TagMedia
     */
    start?: string;
    /**
     * reserved for future video processing
     * @type {string}
     * @memberof TagMedia
     */
    duration?: string;
}
