/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents a media or object tag.
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * tag name.
     * @type {string}
     * @memberof Tag
     */
    name?: string;
    /**
     * tag value.
     * @type {string}
     * @memberof Tag
     */
    value?: string;
    /**
     * tag confidence, if automatically detected, otherwise 1.0.
     * @type {number}
     * @memberof Tag
     */
    confidence?: number;
}
