/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents a recognition results for one or more faces.
 * @export
 * @interface Transform
 */
export interface Transform {
    /**
     * transform request unique identifier.
     * @type {string}
     * @memberof Transform
     */
    transformUuid?: string;
    /**
     * base64 encoded transofrm result image file (jpg or png).
     * @type {string}
     * @memberof Transform
     */
    imageBase64?: string;
}
