/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents a recognition request for one or more faces.
 * @export
 * @interface TransformRequest
 */
export interface TransformRequest {
    /**
     * your API key or d45fd466-51e2-4701-8da8-04351c872236
     * @type {string}
     * @memberof TransformRequest
     */
    apiKey: string;
    /**
     * list of face unique identifiers that should be transformed.
     * @type {Array<string>}
     * @memberof TransformRequest
     */
    facesUuids: Array<string>;
    /**
     * transform action, currently supported action 0 (average faces)
     * @type {number}
     * @memberof TransformRequest
     */
    action: number;
    /**
     * (optional) transform action parameters
     * @type {string}
     * @memberof TransformRequest
     */
    parameters?: string;
}
