/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsageDaily } from './usage-daily';
/**
 * represents an api usage information by day for the past year.
 * @export
 * @interface Usage
 */
export interface Usage {
    /**
     * list of usage statistics by day
     * @type {Array<UsageDaily>}
     * @memberof Usage
     */
    usageDaily?: Array<UsageDaily>;
}
