/* tslint:disable */
/* eslint-disable */
/**
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * represents a daily api usage information.
 * @export
 * @interface UsageDaily
 */
export interface UsageDaily {
    /**
     * year
     * @type {number}
     * @memberof UsageDaily
     */
    year?: number;
    /**
     * month
     * @type {number}
     * @memberof UsageDaily
     */
    month?: number;
    /**
     * day
     * @type {number}
     * @memberof UsageDaily
     */
    day?: number;
    /**
     * processed images count
     * @type {number}
     * @memberof UsageDaily
     */
    images?: number;
}
